config/routes.rb
Rails.application.routes.draw do
  resource :session, only: [:new, :create, :destroy]
  resources :passwords, param: :token
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  root to: "lists#index"

  resources :users, only: [ :new, :create ]
  resources :animes, only: [ :index, :show ]

  resources :lists, only: [ :index, :create, :show ] do
    resources :bookmarks, only: [ :create, :update ]
  end

  resources :bookmarks, only: :destroy
end

app/models/list.rb
class List < ApplicationRecord
  belongs_to :user
  has_many :bookmarks, dependent: :destroy
  has_many :animes, through: :bookmarks, dependent: :destroy

  validates :name, uniqueness: { scope: :user_id }, presence: true
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  allow_unauthenticated_access only: [ :index, :show ]
  before_action :set_list, only: [ :show, :destroy ]

  def index
    @list = List.new

    @lists = List.all

    service = JikanApiService.new()
    @data = service.fetch_data('/v4/top/anime?sfw', { })

  rescue StandardError => e
    render json: { error: e.message }, status: :bad_request
  end

  def show
    @bookmark = Bookmark.new
  end

  def create
    @list = List.new(list_params)
    @list.user = Current.user

    if @list.save
      redirect_to list_path(@list), notice: "List created successfully"
    else
      render :index, status: :unprocessable_entity
    end
  end

  def destroy
  end

  private

  def set_list
    @list = List.find(params[:id])
  end

  def list_params
    params.require(:list).permit(:name)
  end
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/lists/_comment.html.erb
<%=  turbo_frame_tag bookmark.id do %>
  <p class="text-sm"><%= bookmark.comment %></p>
<% end %>

app/views/lists/_list_anime_card.html.erb
<div class="card card-bordered card-compact bg-base-100 shadow-xl relative">
  <figure>
    <%= link_to anime_path(anime) do %>
      <%= image_tag anime.image_url, class: "object-cover" %>
    <% end %>
  </figure>

  <div class="card-body p-4">
    <div class="flex gap-2 justify-between">
      <h2 class="card-title text-base"><%= anime.title %></h2>

      <% if user_owns_list?(list) %>
        <%= link_to bookmark_path(bookmark), data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to remove #{anime.title} from your #{@list.name} list" }, class: "text-danger" do %>
          <%= icon "trash", library: "heroicons", class: "h-5 w-5 text-red-800 transition-transform duration-200 hover:scale-110 hover:text-red-500" %>
        <% end %>
      <% end %>
    </div>

    <div class="flex gap-2 justify-between">
      <%= render partial: "comment", locals: { bookmark: bookmark} %>

      <% if user_owns_list?(list) %>
        <button onclick="document.getElementById('modal_<%= bookmark.id %>').showModal()">
          <%= icon "pencil", library: "heroicons", class: "h-5 w-5 text-black-900 mt-1" %>
        </button>

        <dialog id="modal_<%= bookmark.id %>" class="modal modal-bottom sm:modal-middle">
          <div class="modal-box pt-10">
            <form method="dialog">
              <button class="btn btn-sm btn-circle btn-ghost absolute right-2 top-2">✕</button>
            </form>

            <%= simple_form_for [ list, bookmark ], html: { onsubmit: "document.getElementById('modal_#{bookmark.id}').close();" } do |f| %>
              <%= f.input :comment, as: :text, label: false, input_html: { class: 'textarea textarea-bordered' } %>

              <%= f.submit "Update", class: "btn btn-primary btn-xs float-right"  %>
            <% end %>
          </div>
        </dialog>
      <% end %>
    </div>
  </div>
</div>

app/views/lists/index.html.erb
<div class="max-w-sm md:max-w-3xl mb-20 px-4 pt-4 mx-auto">
  <%= simple_form_for @list, html: { class: "grid grid-cols-3 w-full max-w-sm gap-4 mb-8 sm:hidden"}  do |f| %>
    <%= f.input :name, label: false, placeholder: "List Name", input_html: { class: "input input-bordered w-full max-w-sm" }, wrapper_html: { class: "col-span-2" } %>
    <%= f.submit class: "btn btn-primary" %>
  <% end %>

  <% @lists.each do |list| %>
    <div class="flex flex-col gap-2 mb-4">
      <%= link_to list_path(list), class: "flex flex-col gap-2" do %>
        <p><%= list.name %></p>
      <% end %>

      <%= render partial: "animes/anime_card", locals: { animes: list.animes, list: list } %>
    </div>
  <% end %>

</div>

app/views/lists/show.html.erb
<%= turbo_stream_from "bookmark#{@list.id}_comments" %>

<div class="w-96 mb-20 px-4 pt-4 mx-auto">
  <h1 class="text-4xl"><%= @list.name %></h1>

  <% if user_owns_list?(@list) %>
    <div class="my-8">
      <%= simple_form_for [ @list, @bookmark ] do |f| %>
        <div class="flex flex-col gap-4">
          <%= f.association :anime, label: false, collection: Anime.all.order(:title), prompt: "Select a anime", wrapper: false,  input_html: { class: "select select-bordered w-full max-w-sm"} %>
          <%= f.input :comment, label: false, placeholder: "Enter a comment about the anime" , input_html: { class: "input input-bordered w-full max-w-sm"} %>
        </div>

        <div class="flex justify-end">
          <%= f.submit "Add anime", class: "btn btn-sm btn-primary" %>
        </div>
      <% end %>
    </div>
  <% end %>

  <div class="flex flex-col gap-4">
    <% @list.animes.sort.each do | anime | %>
      <% bookmark = Bookmark.find_by(list: @list, anime: anime) %>

      <%= render partial: "list_anime_card", locals: { anime: anime, bookmark: bookmark, list: @list } %>
    <% end %>
  </div>
</div>