config/routes.rb
Rails.application.routes.draw do
  resource :session, only: [:new, :create, :destroy]
  resources :passwords, param: :token
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  root to: "lists#index"

  resources :users, only: [ :new, :create ]
  resources :animes, only: [ :index, :show ]

  resources :lists, only: [ :index, :create, :show ] do
    resources :bookmarks, only: [ :create, :update ]
  end

  resources :bookmarks, only: :destroy
end

app/views/partials/_bottom_navigation.html.erb
<div class="btm-nav sm:hidden">
  <% if authenticated? %>
    <%= link_to Current.session, data: { turbo_method: :delete }, class: "flex flex-col justify-center items-center" do %>
      <%= icon "arrow-left-start-on-rectangle", library: "heroicons", class: "h-5 w-5" %>
      <span class="btm-nav-label text-xs">Logout</span>
    <% end %>
  <% else  %>
    <%= link_to new_session_path, class: "flex flex-col justify-center items-center" do %>
      <%= icon "arrow-right-start-on-rectangle", library: "heroicons", class: "h-5 w-5" %>
      <span class="btm-nav-label text-xs">Login</span>
    <% end %>
  <% end %>

  <%= link_to lists_path, class: "flex flex-col justify-center items-center" do %>
    <%= icon "queue-list", library: "heroicons", class: "h-5 w-5" %>
    <span class="btm-nav-label text-xs">Lists</span>
  <% end %>

  <%= link_to animes_path, class: "flex flex-col justify-center items-center" do %>
    <%= icon "bookmark-square", library: "heroicons", class: "h-5 w-5" %>
    <span class="btm-nav-label text-xs">Animes</span>
  <% end %>
</div>

app/views/partials/_top_navigation.html.erb
<div class="navbar bg-base-100 hidden justify-between sm:flex w-[48rem] mx-auto">
  <div class="navbar-start">
    <div class="dropdown">
      <div tabindex="0" role="button" class="btn btn-ghost btn-circle">
        <svg
          xmlns="http://www.w3.org/2000/svg"
          class="h-5 w-5"
          fill="none"
          viewBox="0 0 24 24"
          stroke="currentColor">
          <path
            stroke-linecap="round"
            stroke-linejoin="round"
            stroke-width="2"
            d="M4 6h16M4 12h16M4 18h7">
          </path>
        </svg>
      </div>
      <ul
        tabindex="0"
        class="menu menu-sm dropdown-content bg-base-100 rounded-box z-[1] mt-3 w-52 p-2 shadow">
        <li>
          <%= link_to lists_path, class: "flex gap-4" do %>
            <%= icon "home", library: "heroicons", class: "h-5 w-5" %>
            <span class="btm-nav-label text-xs">Lists</span>
          <% end %>
        </li>
        <li>
          <%= link_to animes_path, class: "flex gap-4" do %>
            <%= icon "bookmark-square", library: "heroicons", class: "h-5 w-5" %>
            <span class="btm-nav-label text-xs">Animes</span>
          <% end %>
        </li>
        <li>
          <% if authenticated? %>
            <%= link_to Current.session, data: { turbo_method: :delete }, class: "flex gap-4" do %>
              <%= icon "arrow-left-start-on-rectangle", library: "heroicons", class: "h-5 w-5" %>
              <span class="btm-nav-label text-xs">Logout</span>
            <% end %>
          <% else  %>
            <%= link_to new_session_path, class: "flex gap-4" do %>
              <%= icon "arrow-right-start-on-rectangle", library: "heroicons", class: "h-5 w-5" %>
              <span class="btm-nav-label text-xs">Login</span>
            <% end %>
          <% end %>
        </li>
      </ul>
    </div>
  </div>
  <div class="navbar-center">
    <% if @list %>
      <%= simple_form_for @list, html: { class: "grid-cols-3 w-full max-w-sm gap-4 grid "}  do |f| %>
        <%= f.input :name, label: false, placeholder: "List Name", input_html: { class: "input input-bordered w-full max-w-sm" }, wrapper_html: { class: "col-span-2 mb-0" } %>
        <%= f.submit class: "btn btn-primary" %>
      <% end %>
    <% end %>
  </div>
  <div class="navbar_end">
  </div>
</div>