config/routes.rb
Rails.application.routes.draw do
  resource :session, only: [:new, :create, :destroy]
  resources :passwords, param: :token
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  root to: "lists#index"

  resources :users, only: [ :new, :create ]
  resources :animes, only: [ :index, :show ]

  resources :lists, only: [ :index, :create, :show ] do
    resources :bookmarks, only: [ :create, :update ]
  end

  resources :bookmarks, only: :destroy
end

app/models/anime.rb
class Anime < ApplicationRecord
  has_many :bookmarks
  has_many :lists, through: :bookmarks

  validates :mal_id, presence: true, uniqueness: true
end

app/controllers/animes_controller.rb
class AnimesController < ApplicationController
  allow_unauthenticated_access only: [ :index, :show ]
  before_action :set_anime, only: [ :show ]

  def index
    @top_anime = Anime.order(ranking: :asc).limit(50)
    @currently_airing = Anime.where(airing: true).order(ranking: :asc).limit(50)
  end

  def show
    service = JikanApiService.new()

    @data = service.fetch_data("/v4/anime/#{@anime.mal_id}/full", {})["data"]

  rescue StandardError => e
    render json: { error: e.message }, status: :bad_request
  end

  private

  def set_anime
    @anime = Anime.find(params[:id])
  end
end

app/helpers/anime_helper.rb
module AnimeHelper
end

app/views/animes/_anime_card.html.erb
<div class="flex overflow-x-auto snap-x snap-mandatory space-x-4 scrollbar-hide gap-4">
  <% animes.each do |anime| %>
    <%= link_to controller_name == "animes" ? anime_path(anime) : list_path(list), class: "contents" do %>
      <%= image_tag anime.image_url, class: "h-48 w-32 object-cover rounded-md snap-start" %>
    <% end %>
  <% end %>
</div>

app/views/animes/index.html.erb
<div class="max-w-sm md:max-w-3xl mb-20 px-4 pt-4 mx-auto">

  <h2 class="text-xl">Top 50 Anime</h2>

  <%= render partial: "anime_card", locals: { animes: @top_anime } %>
</div>

<div class="max-w-sm md:max-w-3xl mb-20 px-4 pt-4 mx-auto">
  <h2 class="text-xl">Currently Airing</h2>

  <%= render partial: "anime_card", locals: { animes: @currently_airing } %>
</div>

app/views/animes/show.html.erb
<div class="flex flex-col gap-4 mb-20 mx-auto">
  <div
    class="bg-cover bg-center h-[38rem] flex items-end sm:w-96 sm:mx-auto"
    style="background-image: url('<%= @data["images"]["webp"]["large_image_url"] %>')"
  >
  </div>

  <div class="flex flex-col gap-4 w-96 mx-auto">
    <h1 class="text-xl text-white"><%= @data["title"] %></h1>

    <div class="">
      <% @data["genres"].each do |genre| %>
        <div class="badge badge-primary badge-outline"><%= genre["name"] %></div>
      <% end %>
    </div>

    <div class="flex flex-col gap-2">
      <p class="text-sm">
        <%= @data["score"] %> · <%= @data["rating"] %> · <%= @data["episodes"] %> <%= @data["episodes"] > 1 ? "episodes" : "episode" %>
      </p>

      <p class="text-xs"><%= @data["synopsis"] %></p>
    </div>
  </div>

  <% if @data["trailer"] && @data["trailer"]["embed_url"] %>
    <div class="relative w-96 pb-[56.25%] mx-auto">
      <iframe
        class="absolute top-0 left-0 w-full h-full"
        src="<%= @data["trailer"]["embed_url"] %>"
        frameborder="0"
        allow="accelerometer; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
        allowfullscreen>
      </iframe>
    </div>
  <% end %>
</div>